<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Dhanvi.Modules.Auctions.Domain/Dhanvi.Modules.Auctions.Domain.csproj" /><ProjectReference Include="../../RandomDraws/Dhanvi.Modules.RandomDraws.Application/Dhanvi.Modules.RandomDraws.Application.csproj" /></ItemGroup></Project>
