<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../../Ledger/Dhanvi.Modules.Ledger.Application/Dhanvi.Modules.Ledger.Application.csproj" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dhanvi.Modules.Groups.Application\Dhanvi.Modules.Groups.Application.csproj" />
    <ProjectReference Include="..\Dhanvi.Modules.Groups.Domain\Dhanvi.Modules.Groups.Domain.csproj" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../../Identity/Dhanvi.Modules.Identity.Application/Dhanvi.Modules.Identity.Application.csproj" /></ItemGroup>
<ItemGroup><ProjectReference Include="../../RandomDraws/Dhanvi.Modules.RandomDraws.Application/Dhanvi.Modules.RandomDraws.Application.csproj" /></ItemGroup>
<ItemGroup><ProjectReference Include="../../Auctions/Dhanvi.Modules.Auctions.Infrastructure/Dhanvi.Modules.Auctions.Infrastructure.csproj" /></ItemGroup>
</Project>

