import { createHash } from "node:crypto";

/**
 * Byte-exact port of `System.Text.Json.JsonSerializer` with DEFAULT options, as the .NET backend used it for
 * fingerprints and request hashes (ledger source fingerprints, captured-payment / settled-payout fingerprints,
 * payout provider payload hashes, contribution idempotency request hashes).
 *
 * Existing rows store SHA-256 hashes of those bytes. Replays and idempotent retries after cutover recompute the
 * hash, so any deviation would surface as LEDGER_EVENT_REUSED / IDEMPOTENCY_KEY_REUSED. Verified against
 * golden output generated by .NET 10 (test/unit/dotnet-json.test.ts).
 *
 * Default-options semantics reproduced:
 *  - property names as declared (records: PascalCase; anonymous types: as written), declaration order
 *  - enums as integers, Guid lowercase "D", decimals with their scale preserved ("500.00", "2500.5")
 *  - DateTimeOffset round-trip text with trailing fractional zeros trimmed, offset "+00:00"
 *  - JavaScriptEncoder.Default escaping: only printable ASCII except " & ' + < > ` \ is emitted raw
 */
export class NetDecimal { constructor(readonly text: string) {} }
export class NetInt { constructor(readonly value: number) {} }
export class NetDateTimeOffset { constructor(readonly text: string) {} }

export type NetValue = string | boolean | null | NetDecimal | NetInt | NetDateTimeOffset | NetValue[] | { [key: string]: NetValue };

/** Enum or integer field, serialized as a JSON number. */
export const netInt = (value: number): NetInt => new NetInt(value);
/** Decimal with an explicit scale, e.g. netDecimal(amount.toFixed(2)) for NUMERIC(18,2) columns. */
export const netDecimal = (text: string): NetDecimal => new NetDecimal(normalizeDecimalText(text));
export const netGuid = (id: string): string => id.toLowerCase();

const SHORT_ESCAPES: Record<string, string> = { "\\": "\\\\", "\n": "\\n", "\r": "\\r", "\t": "\\t", "\b": "\\b", "\f": "\\f" };
const ALWAYS_ESCAPED = new Set(['"', "&", "'", "+", "<", ">", "`"]);

export function escapeNetString(value: string): string {
  let out = '"';
  for (let i = 0; i < value.length; i++) {
    const ch = value[i] as string;
    const code = value.charCodeAt(i);
    const short = SHORT_ESCAPES[ch];
    if (short) out += short;
    else if (code >= 0x20 && code <= 0x7e && !ALWAYS_ESCAPED.has(ch)) out += ch;
    else out += "\\u" + code.toString(16).toUpperCase().padStart(4, "0");
  }
  return out + '"';
}

/** .NET decimal text: no exponent, sign kept, scale (trailing zeros) preserved as given. */
function normalizeDecimalText(text: string): string {
  const trimmed = text.trim();
  if (!/^-?\d+(\.\d+)?$/.test(trimmed)) throw new Error(`Not a plain decimal token: ${text}`);
  return trimmed.replace(/^(-?)0+(?=\d)/, "$1");
}

/**
 * Formats an instant for DateTimeOffset JSON. Accepts PostgreSQL UTC text ("2026-09-13 09:38:59.123456+00"),
 * ISO text, or a Date (millisecond precision). Output: "2026-09-13T09:38:59.123456+00:00".
 */
export function netDateTimeOffset(value: string | Date): NetDateTimeOffset {
  let iso: string;
  if (value instanceof Date) iso = value.toISOString();
  else iso = value.trim().replace(" ", "T");
  const match = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,7}))?(Z|[+-]00(?::?00)?)$/.exec(iso);
  if (!match) throw new Error(`Unsupported UTC timestamp text: ${String(value)}`);
  const fraction = (match[2] ?? "").replace(/0+$/, "");
  return new NetDateTimeOffset(`${match[1]}${fraction ? `.${fraction}` : ""}+00:00`);
}

export function serializeNet(value: NetValue): string {
  if (value === null) return "null";
  if (typeof value === "string") return escapeNetString(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (value instanceof NetDecimal) return value.text;
  if (value instanceof NetInt) return String(value.value);
  if (value instanceof NetDateTimeOffset) return `"${value.text}"`;
  if (Array.isArray(value)) return `[${value.map(serializeNet).join(",")}]`;
  return `{${Object.entries(value).map(([k, v]) => `${escapeNetString(k)}:${serializeNet(v)}`).join(",")}}`;
}

/** Convert.ToHexStringLower(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(value))) */
export const netFingerprint = (value: NetValue): string => createHash("sha256").update(serializeNet(value), "utf8").digest("hex");
