<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="../Dhanvi.Modules.Payouts.Application/Dhanvi.Modules.Payouts.Application.csproj" /><ProjectReference Include="../../Identity/Dhanvi.Modules.Identity.Application/Dhanvi.Modules.Identity.Application.csproj" /></ItemGroup></Project>
