// <auto-generated />
using System;
using Dhanvi.Modules.Groups.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhanvi.Modules.Groups.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GroupsDbContext))]
    partial class GroupsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("groups")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dhanvi.Modules.Contributions.Domain.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("OverdueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RecordedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("MembershipId");

                    b.HasIndex("CycleId", "GroupId");

                    b.HasIndex("CycleId", "MembershipId")
                        .IsUnique();

                    b.HasIndex("MembershipId", "GroupId");

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("Contributions", "groups", t =>
                        {
                            t.HasCheckConstraint("CK_Contribution_Amounts", "\"ExpectedAmount\" > 0 AND \"RecordedAmount\" BETWEEN 0 AND \"ExpectedAmount\"");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Contributions.Domain.ContributionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ContributionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Reference");

                    b.HasIndex("ReversesEntryId")
                        .IsUnique()
                        .HasFilter("\"ReversesEntryId\" IS NOT NULL");

                    b.HasIndex("ContributionId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ContributionId", "Reference")
                        .IsUnique()
                        .HasFilter("\"EntryType\" = 'Record'");

                    b.HasIndex("ReversesEntryId", "ContributionId");

                    b.ToTable("ContributionEntries", "groups", t =>
                        {
                            t.HasCheckConstraint("CK_Entry_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Entry_Reversal", "(\"EntryType\" = 'Record' AND \"ReversesEntryId\" IS NULL) OR (\"EntryType\" = 'Reversal' AND \"ReversesEntryId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Cycles.Domain.MonthlyCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ContributionDueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ContributionsCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedContributionPerMember")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ExpectedMemberCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedPoolAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("FullyRecordedMemberCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PayoutDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReadyForSelectionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RecordedContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("SelectionDate")
                        .HasColumnType("date");

                    b.Property<string>("SelectionMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContributionDueDate");

                    b.HasIndex("Status");

                    b.HasIndex("GroupId", "CycleNumber")
                        .IsUnique();

                    b.ToTable("MonthlyCycles", "groups", t =>
                        {
                            t.HasCheckConstraint("CK_Cycle_Dates", "\"ContributionDueDate\" <= \"SelectionDate\" AND \"SelectionDate\" <= \"PayoutDate\"");

                            t.HasCheckConstraint("CK_Cycle_Expected", "\"CycleNumber\" BETWEEN 1 AND \"ExpectedMemberCount\" AND \"ExpectedMemberCount\" BETWEEN 20 AND 50 AND \"ExpectedContributionPerMember\" > 0 AND \"ExpectedPoolAmount\" = \"ExpectedContributionPerMember\" * \"ExpectedMemberCount\"");

                            t.HasCheckConstraint("CK_Cycle_Totals", "\"RecordedContributionAmount\" BETWEEN 0 AND \"ExpectedPoolAmount\" AND \"FullyRecordedMemberCount\" BETWEEN 0 AND \"ExpectedMemberCount\"");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CurrentCycleNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<string>("GroupTimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Asia/Kolkata");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GroupValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MemberLimit")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("RulesLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatorType");

                    b.HasIndex("GroupType");

                    b.HasIndex("GroupValue");

                    b.HasIndex("Status");

                    b.ToTable("Groups", "groups", t =>
                        {
                            t.HasCheckConstraint("CK_Group_Capacity", "\"CurrentMemberCount\" >= 0 AND \"CurrentMemberCount\" <= (\"Rules\"->>'MemberLimit')::int");

                            t.HasCheckConstraint("CK_Group_Rules", "(\"Rules\"->>'MemberLimit')::int BETWEEN 20 AND 50 AND (\"Rules\"->>'GroupValue')::numeric > 0 AND \"DurationMonths\" = (\"Rules\"->>'MemberLimit')::int AND \"MonthlyContribution\" * \"DurationMonths\" = (\"Rules\"->>'GroupValue')::numeric");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("GroupAuditEvents", "groups");
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasReceivedPayout")
                        .HasColumnType("boolean");

                    b.Property<int?>("PayoutCycleNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<int?>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TermsVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TermsVersionId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "SlotNumber")
                        .IsUnique()
                        .HasFilter("\"SlotNumber\" IS NOT NULL");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMemberships", "groups", t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Slot", "\"SlotNumber\" IS NULL OR \"SlotNumber\" BETWEEN 1 AND 50");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("RulesHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RulesSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("GroupRuleVersions", "groups");
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupTermsAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupRuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("RulesHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GroupRuleVersionId");

                    b.HasIndex("MembershipId", "GroupRuleVersionId")
                        .IsUnique();

                    b.ToTable("GroupTermsAcceptances", "groups");
                });

            modelBuilder.Entity("Dhanvi.SharedKernel.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "groups");
                });

            modelBuilder.Entity("Dhanvi.Modules.Contributions.Domain.Contribution", b =>
                {
                    b.HasOne("Dhanvi.Modules.Cycles.Domain.MonthlyCycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Groups.Domain.GroupMembership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Contributions.Domain.ContributionEntry", b =>
                {
                    b.HasOne("Dhanvi.Modules.Contributions.Domain.Contribution", null)
                        .WithMany()
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Contributions.Domain.ContributionEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId", "ContributionId")
                        .HasPrincipalKey("Id", "ContributionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhanvi.Modules.Cycles.Domain.MonthlyCycle", b =>
                {
                    b.HasOne("Dhanvi.Modules.Groups.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupAuditEvent", b =>
                {
                    b.HasOne("Dhanvi.Modules.Groups.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupMembership", b =>
                {
                    b.HasOne("Dhanvi.Modules.Groups.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Groups.Domain.GroupRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("TermsVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupRuleVersion", b =>
                {
                    b.HasOne("Dhanvi.Modules.Groups.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Groups.Domain.GroupTermsAcceptance", b =>
                {
                    b.HasOne("Dhanvi.Modules.Groups.Domain.GroupRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("GroupRuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Groups.Domain.GroupMembership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
