// <auto-generated />
using System;
using Dhanvi.Modules.Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhanvi.Modules.Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260911153737_FinancialLedgerFoundation")]
    partial class FinancialLedgerFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("JournalNumberSequence", "ledger");

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("BusinessTimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DebitTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FeePolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ReversesJournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDate");

                    b.HasIndex("EventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("JournalNumber")
                        .IsUnique();

                    b.HasIndex("PostedAt");

                    b.HasIndex("ReversesJournalEntryId")
                        .IsUnique()
                        .HasFilter("\"ReversesJournalEntryId\" IS NOT NULL");

                    b.HasIndex("EventType", "EventId")
                        .IsUnique();

                    b.ToTable("JournalEntries", "ledger", t =>
                        {
                            t.HasCheckConstraint("CK_Journal_Posted", "\"Status\" = 'POSTED' AND \"LineCount\" >= 2 AND \"DebitTotal\" > 0 AND \"DebitTotal\" = \"CreditTotal\"");

                            t.HasCheckConstraint("CK_Journal_Reversal", "(\"EventType\" = 'AccountingReversal' AND \"ReversesJournalEntryId\" IS NOT NULL AND length(trim(\"ReversalReason\")) > 0) OR (\"EventType\" <> 'AccountingReversal' AND \"ReversesJournalEntryId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuctionResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("SelectionResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AuctionResultId");

                    b.HasIndex("CycleId");

                    b.HasIndex("GroupId");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("SelectionResultId");

                    b.ToTable("JournalLines", "ledger", t =>
                        {
                            t.HasCheckConstraint("CK_Line_Currency", "\"Currency\" = 'INR'");

                            t.HasCheckConstraint("CK_Line_Sides", "(\"DebitAmount\" > 0 AND \"CreditAmount\" = 0) OR (\"CreditAmount\" > 0 AND \"DebitAmount\" = 0)");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LedgerAccounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("CK_Account_Normal", "(\"AccountType\" IN ('Asset','Expense') AND \"NormalBalance\" = 'Debit') OR (\"AccountType\" IN ('Liability','Equity','Revenue') AND \"NormalBalance\" = 'Credit')");

                            t.HasCheckConstraint("CK_Account_Type", "\"AccountType\" IN ('Asset','Liability','Equity','Revenue','Expense')");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.HasOne("Dhanvi.Modules.Ledger.Domain.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.JournalLine", b =>
                {
                    b.HasOne("Dhanvi.Modules.Ledger.Domain.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Ledger.Domain.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
