// <auto-generated />
using System;
using Dhanvi.Modules.Payouts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhanvi.Modules.Payouts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayoutsDbContext))]
    partial class PayoutsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payouts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaskedAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PayoutObligationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderFundAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderPayoutId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPayoutId")
                        .IsUnique();

                    b.HasIndex("PayoutObligationId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("PayoutObligationId", "RequestKey")
                        .IsUnique();

                    b.ToTable("PayoutAttempts", "payouts", t =>
                        {
                            t.HasCheckConstraint("CK_Attempt_Money", "\"Amount\" > 0 AND \"Currency\" = 'INR' AND \"Provider\" = 'FAKE'");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutBeneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ifsc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("MaskedAccountNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderFundAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderFundAccountId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PayoutBeneficiaries", "payouts");
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PayoutObligationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayoutObligationId", "CreatedAt");

                    b.ToTable("PayoutReconciliationHistory", "payouts");
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationJournalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuctionResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayoutType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SelectionResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SettlementJournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("CycleId", "MembershipId")
                        .IsUnique()
                        .HasFilter("\"PayoutType\" = 'MemberAuctionBenefit'");

                    b.HasIndex("CycleId", "PayoutType")
                        .IsUnique()
                        .HasFilter("\"PayoutType\" IN ('WinnerPayout','PlatformFeeSettlement')");

                    b.HasIndex("CycleId", "PayoutType", "SourceId")
                        .IsUnique();

                    b.ToTable("PayoutObligations", "payouts", t =>
                        {
                            t.HasCheckConstraint("CK_Payout_Money", "\"Amount\" > 0 AND \"Currency\" = 'INR'");

                            t.HasCheckConstraint("CK_Payout_Recipient", "(\"PayoutType\" = 'PlatformFeeSettlement' AND \"UserId\" IS NULL AND \"MembershipId\" IS NULL) OR (\"PayoutType\" IN ('WinnerPayout','MemberAuctionBenefit') AND \"UserId\" IS NOT NULL AND \"MembershipId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Payout_Settled", "(\"Status\" = 'Succeeded') = (\"SettledAt\" IS NOT NULL AND \"SettlementJournalId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutProviderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Matched")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PayoutAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayoutObligationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderPayoutId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PayoutAttemptId");

                    b.HasIndex("PayoutObligationId");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("PayoutProviderEvents", "payouts");
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Infrastructure.FakeProviderPayout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FundAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("FakeProviderPayouts", "payouts");
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutAttempt", b =>
                {
                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutBeneficiary", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutObligation", null)
                        .WithMany()
                        .HasForeignKey("PayoutObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutHistory", b =>
                {
                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutObligation", null)
                        .WithMany()
                        .HasForeignKey("PayoutObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutObligation", b =>
                {
                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutBeneficiary", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhanvi.Modules.Payouts.Domain.PayoutProviderEvent", b =>
                {
                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutAttempt", null)
                        .WithMany()
                        .HasForeignKey("PayoutAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhanvi.Modules.Payouts.Domain.PayoutObligation", null)
                        .WithMany()
                        .HasForeignKey("PayoutObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
